apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fs
  namespace: d7-d01
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-fs
  template:
    metadata:
      labels:
        app: nginx-fs
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
